name: Water Temperature

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  water:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install requests
        run: |
          pip install requests

      - name: Hämta vattentemperatur
        run: |
          python3 test_vatten.py

      - name: Commit water_temp.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add water_temp.json

          git commit -m "Update water temperature" || true

          git push
